site_name: StephanGR's Documentation

nav:
  - Home: index.md
  - Proxmox:
    - proxmox/index.md
    - Installation: proxmox/installation/index.md
    - Configuration: proxmox/configuration/index.md
  - Docker:
    - docker/index.md
    - Wireguard Frigate and NAT: docker/wireguard_frigate_nat/index.md
  - ISP:
    - isp/index.md
    - How to use UDM PRO SE instead of Orange LIVEBOX ?: isp/bypass-livebox/index.md

theme:
  name: material
  font:
    text: Roboto
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.tracking
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/stephangr

plugins:
  - search:
      lang: en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
